### ISSUE TITLE
componentWillUpdate is deprecated

### ISSUE THREAD

**Issue by xstable** [gusgard/react-native-grid-list#12]
RN 0.60.5

I got the warning, that componentWillUpdate is deprecated.

**Comment by gusgard** [comment]
Thanks, I will update it soon

**Comment by xstable** [comment]
https://github.com/gusgard/react-native-grid-list/pull/13

**Comment by gusgard** [comment]
thanks

**Comment by eastcoastcoder** [comment]
Sorry could we reopen this?
This isn't quite the same. componentDidUpdate actually takes prevProps as its first argument, meaning this refresh is off by one.
From the docs: [https://reactjs.org/docs/react-component.html#componentdidupdate](url)

```js
componentDidUpdate(prevProps) {
  // Typical usage (don't forget to compare props):
  if (this.props.userID !== prevProps.userID) {
    this.fetchData(this.props.userID);
  }
}
```

I've been playing around but still can't seem to get it to re-render on time. Maybe this needs to be getDerivedStateFromProps? [https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops](url)

I just rolled back to 1.0.9 for now.
