### ISSUE TITLE
Why is the data prop required?

### ISSUE THREAD

**Issue by dragonfire1119** [gusgard/react-native-grid-list#8]
When I have a empty array at the time. Shouldn't it just render the ListEmptyComponent & not throw a warning?

**Comment by gusgard** [comment]
Hi, yes you are right, I will refactor this week 👍

**Comment by gusgard** [comment]
Updated @dragonfire1119

**Comment by dragonfire1119** [comment]
@gusgard wow thanks for getting to it quick! Really appreciate it! I'll work on getting it updated in my product soon!
